"""empty message

Revision ID: 15121bfaf373
Revises: a63ff5c8e09f
Create Date: 2019-01-05 22:06:03.077318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15121bfaf373'
down_revision = 'a63ff5c8e09f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('receiver_name', sa.String(length=50), nullable=True))
    op.add_column('transactions', sa.Column('receiver_phone', sa.String(length=14), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'receiver_phone')
    op.drop_column('transactions', 'receiver_name')
    # ### end Alembic commands ###
