"""empty message

Revision ID: 2fab6bf23dce
Revises: 89b59ad5a63a
Create Date: 2019-01-05 15:36:24.180647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fab6bf23dce'
down_revision = '89b59ad5a63a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('merchant', sa.Column('address', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('merchant', 'address')
    # ### end Alembic commands ###
