"""empty message

Revision ID: 89b59ad5a63a
Revises: b64e3f8af7ed
Create Date: 2019-01-05 14:45:41.662131

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '89b59ad5a63a'
down_revision = 'b64e3f8af7ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('merchant', 'bank_account',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('merchant', 'bank_account_name',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('merchant', 'bank_name',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.drop_column('merchant', 'phone_number')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('merchant', sa.Column('phone_number', mysql.VARCHAR(length=50), nullable=False))
    op.alter_column('merchant', 'bank_name',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('merchant', 'bank_account_name',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('merchant', 'bank_account',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###
