"""empty message

Revision ID: a63ff5c8e09f
Revises: e64de60aaff0
Create Date: 2019-01-05 19:06:50.252033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a63ff5c8e09f'
down_revision = 'e64de60aaff0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insurance_method',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('insurance_method', sa.String(length=50), nullable=False),
    sa.Column('insurance_price', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shipment_method',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shipment_method', sa.String(length=50), nullable=False),
    sa.Column('shipment_price', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('transactions', sa.Column('insurance_method_id', sa.Integer(), nullable=False))
    op.add_column('transactions', sa.Column('insurance_price', sa.Float(), nullable=True))
    op.add_column('transactions', sa.Column('receiver_address', sa.String(length=500), nullable=True))
    op.add_column('transactions', sa.Column('shipment_method_id', sa.Integer(), nullable=False))
    op.add_column('transactions', sa.Column('shipment_price', sa.Float(), nullable=True))
    op.create_foreign_key(None, 'transactions', 'insurance_method', ['insurance_method_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'transactions', 'shipment_method', ['shipment_method_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'shipment_price')
    op.drop_column('transactions', 'shipment_method_id')
    op.drop_column('transactions', 'receiver_address')
    op.drop_column('transactions', 'insurance_price')
    op.drop_column('transactions', 'insurance_method_id')
    op.drop_table('shipment_method')
    op.drop_table('insurance_method')
    # ### end Alembic commands ###
