"""empty message

Revision ID: e64de60aaff0
Revises: 2fab6bf23dce
Create Date: 2019-01-05 16:39:12.697647

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e64de60aaff0'
down_revision = '2fab6bf23dce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('transaction_detail_ibfk_2', 'transaction_detail', type_='foreignkey')
    op.drop_column('transaction_detail', 'payment_method_id')
    op.add_column('transactions', sa.Column('payment_method_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'transactions', 'payment_method', ['payment_method_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'payment_method_id')
    op.add_column('transaction_detail', sa.Column('payment_method_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.create_foreign_key('transaction_detail_ibfk_2', 'transaction_detail', 'payment_method', ['payment_method_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
